SOURCE_IMAGE_REPO = os.getenv("SOURCE_IMAGE_REPO", default='your-registry.io/project')

allow_k8s_contexts(k8s_context())

k8s_custom_deploy(
    'acme-fitness-payment',
    apply_cmd = "tanzu apps workload apply acme-fitness-payment " +
                " --local-path ." +
                " --source-image " + SOURCE_IMAGE_REPO + "/acme-fitness-payment-source" +
                " --type web" +
                " --label app.kubernetes.io/part-of=acme-fitness" +
                " --label tanzu.app.live.view=true" +
                " --label tanzu.app.live.view.application.name=acme-fitness-payment" +
				" --annotation autoscaling.knative.dev/minScale=1" +
                " --yes >/dev/null" +
                " && " +
                "kubectl get workload acme-fitness-payment -o yaml",
    delete_cmd = "tanzu apps workload delete acme-fitness-payment --yes",
    deps = ['src', 'build.gradle'],
    container_selector = 'workload',
    live_update = [
      sync('./build/classes', '/workspace/BOOT-INF/classes')
    ]
)

k8s_resource('acme-fitness-payment',
			extra_pod_selectors=[{'serving.knative.dev/service': 'acme-fitness-payment'}])

update_settings(max_parallel_updates=3,
				k8s_upsert_timeout_secs=90,
				suppress_unused_image_warnings=None)
