---
apiVersion: tanzu.vmware.com/v1
kind: SpringCloudGatewayRouteConfig
metadata:
  name: acme-fitness-payment
spec:
  service:
    name: acme-fitness-payment
    ssoEnabled: true
    filters:
      - StripPrefix=0
  routes:
    - predicates:
        - Path=/pay
        - Method=POST
      tokenRelay: true
      tags:
        - payment
---
apiVersion: tanzu.vmware.com/v1
kind: SpringCloudGatewayMapping
metadata:
  name: acme-fitness-payment
spec:
  gatewayRef:
    name: acme-fitness-gateway
  routeConfigRef:
    name: acme-fitness-payment