apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: acme-fitness-catalog
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: acme-fitness
    networking.knative.dev/visibility: cluster-local
spec:
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
  serviceClaims:
    - name: db
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: acme-fitness-catalog-db
  source:
    git:
      url: https://github.com/scottfrederick/acme-fitness-store
      ref:
        branch: tap-1.1
    subPath: "apps/acme-catalog"
