---
apiVersion: tanzu.vmware.com/v1
kind: SpringCloudGatewayRouteConfig
metadata:
  name: acme-fitness-order
spec:
  service:
    name: acme-fitness-order
    # ssoEnabled: true
    filters:
      - StripPrefix=0
  routes:
    - predicates:
        - Path=/order/add/{userId}
        - Method=POST
      tokenRelay: true
      tags:
        - order
    - predicates:
        - Path=/order/{userId}
        - Method=GET
      tokenRelay: true
      tags:
        - order
---
apiVersion: tanzu.vmware.com/v1
kind: SpringCloudGatewayMapping
metadata:
  name: acme-fitness-order
spec:
  gatewayRef:
    name: acme-fitness-gateway
  routeConfigRef:
    name: acme-fitness-order