#@ load("@ytt:data", "data")

---
apiVersion: sso.apps.tanzu.vmware.com/v1alpha1
kind: ClientRegistration
metadata:
  name: acme-fitness-gateway-client-credentials
spec:
  authServerSelector:
    matchLabels:
      name: acme-fitness-authserver
  redirectURIs:
    - #@ "http://acme-fitness.{}.{}/login/oauth2/code/sso".format(data.values.namespace,data.values.baseUrl)
  requireUserConsent: false
  clientAuthenticationMethod: basic
  authorizationGrantTypes:
    - "client_credentials"
    - "authorization_code"
  scopes:
    - name: "openid"
    - name: "email"
    - name: "profile"
    - name: "roles"
    - name: "message.read"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: acme-fitness-authserver-jwk-uri
  labels:
    app.kubernetes.io/part-of: acme-fitness
data:
  application.yml: |
    spring:
      security:
        oauth2:
          resourceserver:
            jwt:
              jwk-set-uri: #@ "http://acme-fitness-authserver.{}.{}/oauth2/jwks".format(data.values.namespace,data.values.baseUrl)