if 'SOURCE_IMAGE_REPO' not in os.environ:
    fail("environment variable SOURCE_IMAGE_REPO must be set")

SOURCE_IMAGE_REPO = os.getenv("SOURCE_IMAGE_REPO")

allow_k8s_contexts(k8s_context())

k8s_custom_deploy(
    'acme-fitness-cart',
    apply_cmd = "tanzu apps workload apply acme-fitness-cart " +
                " --local-path ." +
                " --source-image " + SOURCE_IMAGE_REPO + "/acme-fitness-cart-source" +
                " --type web" +
                " --label app.kubernetes.io/part-of=acme-fitness" +
                " --label tanzu.app.live.view=true" +
                " --label tanzu.app.live.view.application.name=acme-fitness-cart" +
				" --annotation autoscaling.knative.dev/minScale=1" +
				" --env AUTH_MODE=0" +
                " --yes >/dev/null" +
                " && " +
                "kubectl get workload acme-fitness-cart -o yaml",
    delete_cmd = "tanzu apps workload delete acme-fitness-cart --yes",
    deps = ['cart.py', 'redis_conn.py', 'requirements.txt'],
    container_selector = 'workload',
)

k8s_resource('acme-fitness-cart',
			extra_pod_selectors=[{'serving.knative.dev/service': 'acme-fitness-cart'}])

update_settings(max_parallel_updates=3,
				k8s_upsert_timeout_secs=90,
				suppress_unused_image_warnings=None)
